steps:

- name: python:3.11
  args:
    - python
    - "-c"
    - "import sys; sys.stdout.write(f'__version__ = \"{sys.argv[1]}\"')"
    - "${_VERSION}"  # Pass the version as a parameter
  id: SetVersion


# Step 2: Build the package
- name: python:3.11
  args:
    - bash
    - "-c"
    - |
        python setup.py sdist bdist_wheel --version=${_VERSION}
        echo "Build completed successfully"
  id: BuildPackage

# Step 3: Publish the package
- name: python:3.9
  args:
    - bash
    - "-c"
    - |
        pip install --upgrade setuptools wheel twine keyrings.google-artifactregistry-auth && \
        python -m twine upload \
        --verbose \
        --repository-url https://${_LOCATION}-python.pkg.dev/gpu-reservation-sarvam/sarvam-python-ci/ \
        dist/*
  id: PublishToArtifactRegistry

substitutions:
  _LOCATION: europe-west4
  _VERSION: $TAG_NAME

options:
  dynamicSubstitutions: true
